name: Test - Install Packages
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  jax:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        jax-version: [
          0.4.31,
          0.4.30,
          0.4.29,
          0.4.28,
          0.4.27,
          0.4.26,
          0.4.25,
          0.4.24,
          0.4.23,
          0.4.22,
          0.4.21,
          0.4.20,
          0.4.19,
          0.4.18,
          0.4.17,
          0.4.16,
          0.4.14,
          0.4.13,
          0.4.12,
          0.4.11,
          0.4.10,
          0.4.9,
          0.4.7,
          0.4.6,
          0.4.5,
          0.4.4,
          0.4.3,
          0.4.2,
          0.4.1,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Find closest valid version
        id: python-package
        uses: durandtibo/python-package-action@v0.2.0
        with:
          package-name: 'jax'
          package-version: ${{ matrix.jax-version }}
          python-version: ${{ matrix.python-version }}

      - name: Print closest valid version
        run: echo '${{ toJSON(steps.python-package.outputs) }}'

      - name: Install packages
        run: |
          pip install "feu[fire]>=0.1.0"
          python -m feu install --package=jax --version=${{ steps.python-package.outputs.closest-valid-version }}

      - name: Run functional tests
        run: |
          pip install pytest coola
          python -m pytest tests/functional


  numpy:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        numpy-version: [
          2.1.1,
          2.1.0,
          2.0.2,
          2.0.1,
          2.0.0,
          1.26.4,
          1.26.3,
          1.26.2,
          1.26.1,
          1.26.0,
          1.25.2,
          1.25.1,
          1.25.0,
          1.24.3,
          1.24.2,
          1.24.1,
          1.24.0,
          1.23.5,
          1.23.0,
          1.22.4,
          1.22.0,
          1.21.6,
          1.21.0,
          1.20.3,
          1.20.0,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Find closest valid version
        id: python-package
        uses: durandtibo/python-package-action@v0.2.0
        with:
          package-name: 'numpy'
          package-version: ${{ matrix.numpy-version }}
          python-version: ${{ matrix.python-version }}

      - name: Print closest valid version
        run: echo '${{ toJSON(steps.python-package.outputs) }}'

      - name: Install packages
        run: |
          pip install numpy==${{ steps.python-package.outputs.closest-valid-version }}

      - name: Run functional tests
        run: |
          pip install pytest coola
          python -m pytest tests/functional


  pandas:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        pandas-version: [
          2.2.2,
          2.2.1,
          2.2.0,
          2.1.4,
          2.1.3,
          2.1.2,
          2.1.1,
          2.1.0,
          2.0.3,
          2.0.2,
          2.0.1,
          2.0.0,
          1.5.3,
          1.5.2,
          1.5.1,
          1.5.0,
          1.4.4,
          1.4.3,
          1.4.2,
          1.4.1,
          1.4.0,
          1.3.5,
          1.3.4,
          1.3.3,
          1.3.2,
          1.3.1,
          1.3.0,
          1.2.5,
          1.2.0,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Find closest valid version
        id: python-package
        uses: durandtibo/python-package-action@v0.2.0
        with:
          package-name: 'pandas'
          package-version: ${{ matrix.pandas-version }}
          python-version: ${{ matrix.python-version }}

      - name: Print closest valid version
        run: echo '${{ toJSON(steps.python-package.outputs) }}'

      - name: Install packages
        run: |
          pip install "feu[fire]>=0.1.0"
          python -m feu install --package=pandas --version=${{ steps.python-package.outputs.closest-valid-version }}

      - name: Run functional tests
        run: |
          pip install pytest coola
          python -m pytest tests/functional


  pyarrow:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        pyarrow-version: [
          17.0.0,
          16.1.0,
          16.0.0,
          15.0.2,
          15.0.1,
          15.0.0,
          14.0.2,
          14.0.1,
          14.0.0,
          13.0.0,
          12.0.1,
          12.0.0,
          11.0.0,
          10.0.1,
          10.0.0,
          9.0.0,
          8.0.0,
          7.0.0,
          6.0.1,
          6.0.0,
          5.0.0,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Find closest valid version
        id: python-package
        uses: durandtibo/python-package-action@v0.2.0
        with:
          package-name: 'pyarrow'
          package-version: ${{ matrix.pyarrow-version }}
          python-version: ${{ matrix.python-version }}

      - name: Print closest valid version
        run: echo '${{ toJSON(steps.python-package.outputs) }}'

      - name: Install packages
        run: |
          pip install "feu[fire]>=0.1.0"
          python -m feu install --package=pyarrow --version=${{ steps.python-package.outputs.closest-valid-version }}

      - name: Run functional tests
        run: |
          pip install pytest coola
          python -m pytest tests/functional


  torch:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        torch-version: [
          2.4.1,
          2.4.0,
          2.3.1,
          2.3.0,
          2.2.2,
          2.2.1,
          2.2.0,
          2.1.2,
          2.1.1,
          2.1.0,
          2.0.1,
          2.0.0,
          1.13.1,
          1.13.0,
          1.12.1,
          1.12.0,
          1.11.0,
          1.10.2,
          1.10.1,
          1.10.0,
          1.9.1,
          1.9.0,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Find closest valid version
        id: python-package
        uses: durandtibo/python-package-action@v0.2.0
        with:
          package-name: 'torch'
          package-version: ${{ matrix.torch-version }}
          python-version: ${{ matrix.python-version }}

      - name: Print closest valid version
        run: echo '${{ toJSON(steps.python-package.outputs) }}'

      - name: Install packages
        run: |
          pip install "feu[fire]>=0.1.0"
          python -m feu install --package=torch --version=${{ steps.python-package.outputs.closest-valid-version }}

      - name: Run functional tests
        run: |
          pip install pytest coola
          python -m pytest tests/functional
